apiVersion: v1
kind: Service
metadata:
  name: deconz-{{ required "Required host, e.g. --set host=pi4a" .Values.host }}
  labels:
    app: deconz-{{ .Values.host }}
  annotations:
    metallb.io/loadBalancerIPs: {{ required "Required loadBalancerIPs, e.g. --set loadBalancerIPs=192.168.1.26" .Values.loadBalancerIPs }}
spec:
  selector:
    app: deconz-{{ .Values.host }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: ws
    port: 443
    targetPort: 443
    protocol: TCP
  - name: vnc
    port: 5900
    targetPort: 5900
    protocol: TCP
  type: LoadBalancer
  externalTrafficPolicy: Local
