image:
  repository: ghcr.io/koenkk/zigbee2mqtt
  tag: 2.12.1@sha256:80f7f04f72a99e4c4ef51ef7e98ee736edba6db0ecbb7abc626d0c4b0f1871f1
port: 8080
timezone: Europe/Berlin
nfs:
  server: 192.168.1.4
  path: "/nfs/zigbee2mqtt"
